### PR TITLE
fix(status): enable --booted option to only show the current deployment

### LINKED ISSUE #465: `bootc status --booted` does not show booted deployment only
`bootc status --booted` shows both `booted` and `rollback` deployments.
bootc version: `bootc-202404082017.g593a932258-1.el9.x86_64`
```
    apiVersion: org.containers.bootc/v1alpha1
    kind: BootcHost
    metadata:
      name: host
    spec:
      image:
        image: quay.io/redhat_emp1/centos-bootc-dev-test:efvi
        transport: registry
      bootOrder: default
    status:
      staged: null
      booted:
        image:
          image:
            image: quay.io/redhat_emp1/centos-bootc-dev-test:efvi
            transport: registry
          version: stream9.20240408.0
          timestamp: null
          imageDigest: sha256:321f50bfe1d7357b96c5ae1bd167a73c8e35da3148c588647e28706af2f84ba6
        cachedUpdate: null
        incompatible: false
        pinned: false
        ostree:
          checksum: ef81c60b6c0e7c3646b2065b8a2fa820583d047dff2af5bb393f2de3a7fdb159
          deploySerial: 0
      rollback:
        image:
          image:
            image: localhost/centos-bootc-dev-test:efvi
            transport: registry
          version: stream9.20240408.0
          timestamp: null
          imageDigest: sha256:8567933fb840bd38804f9f0226d6edec9630d46506cdf83347152ee6961ec621
        cachedUpdate: null
        incompatible: false
        pinned: false
        ostree:
          checksum: daf537165510cd1c77b389a38d3cce5c0cd20bb83594219b3d57b6df833376dd
          deploySerial: 0
      rollbackQueued: false
      type: bootcHost
```

### PR DESCRIPTION
**Pull request by p5**
The existing code didn't take into account the --booted option, so always showed the staged, current and rollback deployments.  This correctly wires through the --booted option to only show that deployment.

Stubs have been left in the code should we wish to enable options to show only the rollback or staged options (--rollback / --staged).

I tried to make the implementation not specific to --booted, so added the Slot enum as an input.  This meant making that enum public.  Please let me know if you would prefer a different approach.

No docs changes were required since the flag is already present.

Please find below the different outputs:

<details>

```
bootc-status-booted-only on  bootc-status-booted-only via 🦀 took 2s 
❯ sudo ./target/debug/bootc status --booted
[sudo] password for admin: 
● Booted image: ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open
        Digest: sha256:82de1647a00fd1f7674d268c9aaa33127a09139ac3206c5d71c8e0926846304d
       Version: 250317 (2025-03-17T01:45:07Z)

bootc-status-booted-only on  bootc-status-booted-only via 🦀 took 3s 
❯ sudo ./target/debug/bootc status         
● Booted image: ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open
        Digest: sha256:82de1647a00fd1f7674d268c9aaa33127a09139ac3206c5d71c8e0926846304d
       Version: 250317 (2025-03-17T01:45:07Z)

  Rollback image: ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open
          Digest: sha256:2b6be3a574af416fa7adb8a1217e408aabe18ab15e6e9a401e180a9d1b40bb44
         Version: 250315 (2025-03-15T01:45:07Z)

bootc-status-booted-only on  bootc-status-booted-only via 🦀 
❯ sudo ./target/debug/bootc status --json  
{"apiVersion":"org.containers.bootc/v1","kind":"BootcHost","metadata":{"name":"host"},"spec":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"bootOrder":"default"},"status":{"staged":null,"booted":{"image":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"version":"250317","timestamp":"2025-03-17T01:45:07Z","imageDigest":"sha256:82de1647a00fd1f7674d268c9aaa33127a09139ac3206c5d71c8e0926846304d"},"cachedUpdate":null,"incompatible":false,"pinned":false,"store":"ostreeContainer","ostree":{"checksum":"bf1483336d5d20bd453c07606c65066147eec7149b3f8b269c8f4d167df8d2f3","deploySerial":0}},"rollback":{"image":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"version":"250315","timestamp":"2025-03-15T01:45:07Z","imageDigest":"sha256:2b6be3a574af416fa7adb8a1217e408aabe18ab15e6e9a401e180a9d1b40bb44"},"cachedUpdate":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"version":"250317","timestamp":"2025-03-17T01:45:07Z","imageDigest":"sha256:82de1647a00fd1f7674d268c9aaa33127a09139ac3206c5d71c8e0926846304d"},"incompatible":false,"pinned":false,"store":"ostreeContainer","ostree":{"checksum":"6fb01556d574856633568b7db7b5760f0b23890f510e0da05dcaadc3023c2443","deploySerial":0}},"rollbackQueued":false,"type":"bootcHost"}}%                                                                                                                   
bootc-status-booted-only on  bootc-status-booted-only via 🦀 
❯ sudo ./target/debug/bootc status --booted --json
{"apiVersion":"org.containers.bootc/v1","kind":"BootcHost","metadata":{"name":"host"},"spec":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"bootOrder":"default"},"status":{"staged":null,"booted":{"image":{"image":{"image":"ghcr.io/rsturla/eternal-linux/lumina:stable-nvidia-open","transport":"registry","signature":"containerPolicy"},"version":"250317","timestamp":"2025-03-17T01:45:07Z","imageDigest":"sha256:82de1647a00fd1f7674d268c9aaa33127a09139ac3206c5d71c8e0926846304d"},"cachedUpdate":null,"incompatible":false,"pinned":false,"store":"ostreeContainer","ostree":{"checksum":"bf1483336d5d20bd453c07606c65066147eec7149b3f8b269c8f4d167df8d2f3","deploySerial":0}},"rollback":null,"rollbackQueued":false,"type":"bootcHost"}}%                                                                                                                                          

```

</details>

Closes #465

---

This is my first "real" Rust PR, so please be harsh.

### CODE REVIEW

**Comment by p5** [comment]
Marked as draft as I think it could be improved.
This does fix the issue, though still results in unnecessary calls to get the rollback and staged deployments.

File: lib/src/status.rs [hunk 1]
```diff
@@ -200,6 +200,7 @@ pub(crate) fn get_status_require_booted(
 pub(crate) fn get_status(
     sysroot: &Storage,
     booted_deployment: Option<&ostree::Deployment>,
+    slot: Option<Slot>,
```
Comment (cgwalters) [inline lib/src/status.rs:203]: I'm OK with this as is although...it feels like it'd be cleaner to have a method that filters the status after we gather it?

Something like this:

```
impl Host {
  fn filter_to_slot(&mut self, slot: Slot) {
     ...
}
```

It'd require less Option-juggling and also we wouldn't need to change all the callers.

**Review by cgwalters — COMMENTED** [review]
Thanks for working on this!

File: lib/src/status.rs (hunk 1 above)
Comment (cgwalters) [reply lib/src/status.rs:203]: The other alternative is to pass the slot down to the rendering code instead.

Comment (p5) [reply lib/src/status.rs]: Force pushed the code into 1418f0b.  There wasn't much need in keeping the old commits around since all bar one line was changed.

Confirmed this still does work as expected, so please let me know if there's anything you feel could do with changing.

**Review by cgwalters — APPROVED** [review]
Nice, thanks!

optional followup: I think we could unit test and/or integration test (`001-test-status.nu` this pretty easily, but I think this is obvious enough to merge as is.

**Comment by p5** [comment]
> Nice, thanks!
> 
> optional followup: I think we could unit test and/or integration test (`001-test-status.nu` this pretty easily, but I think this is obvious enough to merge as is.

Awesome!  
Sure, I'll try to create a follow-up PR in the next day or so to add some tests.

**Comment by castrojo** [comment]
First code contribution to a CNCF project for Robert! 🥳
